name: Run Tests

on:
  workflow_dispatch:
    inputs:
      deployment_target: 
        description: choose tests set
        required: true
        type: choice
        default: smoke
        options: 
          - smoke
          - regression
          - extended
          - all
        

jobs:
  run-tests:
    runs-on: ubuntu-latest
    name: Run autotests
    steps: 
      - name: Checkout autotests
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - name: Install dependensis
        run: pip install -r requirements.txt
      - name: run tests
        run: pytest
